CREATE TABLE tb_abrigo(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(250) NOT NULL,
	LOGRADOURO VARCHAR(250) NOT NULL,
	BAIRRO VARCHAR(250) NOT NULL,
	ESTADO VARCHAR(20) NOT NULL
)
