CREATE TABLE tb_pet(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(250) NOT NULL,
	SOBRE VARCHAR(250) NOT NULL,
	IDADE VARCHAR(250) NOT NULL,
	ADOTADO BOOLEAN NOT NULL,
	IMAGEM LONGBLOB NOT NULL,
	LOGRADOURO VARCHAR(250) NOT NULL,
	BAIRRO VARCHAR(250) NOT NULL,
	ESTADO VARCHAR(20) NOT NULL,
	ID_ABRIGO BIGINT NOT NULL,
	FOREIGN KEY(ID_ABRIGO) REFERENCES tb_abrigo(ID)
)