
ALTER TABLE tb_tutor ADD foto LONGBLOB NULL;
ALTER TABLE tb_tutor ADD telefone VARCHAR(20) NULL;

ALTER TABLE tb_tutor ADD LOGRADOURO VARCHAR(250) NULL;
ALTER TABLE tb_tutor ADD BAIRRO VARCHAR(250) NULL;
ALTER TABLE tb_tutor ADD ESTADO VARCHAR(20) NULL;
ALTER TABLE tb_tutor ADD SOBRE VARCHAR(250) NULL;